### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by jamalsoueidan** [chunliu/typescript-react-hot-reload#4]
Hello,

I just tried your repos out, and im getting this error:

```WARNING in ./components/pages/TodoPage.tsx
Module Warning (from ../node_modules/tslint-loader/index.js):
[81, 40]: expected nospace before colon in call-signature

 @ ./components/routes.tsx 4:0-44 15:61-69
 @ ./components/App.tsx
 @ ./index.tsx
 @ multi ../node_modules/webpack-dev-server/client?http://localhost:8080 webpack/hot/dev-server webpack-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./index.tsx
```

and it refresh everytime i change any code?

Is this supposed to work this way?

**Comment by chunliu** [comment]
@jamalsoueidan This is a lint warning TodoPage.tsx. I have fixed it. 
It is supposed to refresh automatically every time you change your code and save it. This is how the hot reload module works, so you don't have to stop the webpack dev server, and re-run npm start every time when you make some code changes.
